import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Navbar  from "../components/Navbar";
import HeroSection from "../components/HeroSection";
import Herodown from "../components/Herodown";
import BrandTrust from "../components/BrandTrust";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="bg-black text-white min-h-screen">
        {/* Normal header container, NO fixed or sticky positioning here */}
        <header className="w-full">
          <Navbar />
        </header>
        
        {/* Removed the hardcoded padding since the top bar isn't floating anymore */}
        <main className="relative">
          <HeroSection />
          <Herodown />
          <BrandTrust />
          {children}
        </main>
      </body>
    </html>
  );
}